# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'TadaSonarQube'
    scannerMode: 'MSBuild'
    projectKey: 'TadaNomina_TadaNomina_AY4-Sz5r39RMu7PzHEnN'
    projectName: 'TadaNomina'

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '500'