//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.ServiceReferenceTP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaTimbrado", Namespace="http://schemas.datacontract.org/2004/07/PacUtils.Core")]
    [System.SerializableAttribute()]
    public partial class RespuestaTimbrado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CadenaTimbreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CfdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DescripcionErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CadenaTimbre {
            get {
                return this.CadenaTimbreField;
            }
            set {
                if ((object.ReferenceEquals(this.CadenaTimbreField, value) != true)) {
                    this.CadenaTimbreField = value;
                    this.RaisePropertyChanged("CadenaTimbre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cfdi {
            get {
                return this.CfdiField;
            }
            set {
                if ((object.ReferenceEquals(this.CfdiField, value) != true)) {
                    this.CfdiField = value;
                    this.RaisePropertyChanged("Cfdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DescripcionError {
            get {
                return this.DescripcionErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionErrorField, value) != true)) {
                    this.DescripcionErrorField = value;
                    this.RaisePropertyChanged("DescripcionError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid {
            get {
                return this.UuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidField, value) != true)) {
                    this.UuidField = value;
                    this.RaisePropertyChanged("Uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valido {
            get {
                return this.ValidoField;
            }
            set {
                if ((this.ValidoField.Equals(value) != true)) {
                    this.ValidoField = value;
                    this.RaisePropertyChanged("Valido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCancelacion", Namespace="http://schemas.datacontract.org/2004/07/PacUtils.Core")]
    [System.SerializableAttribute()]
    public partial class RespuestaCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcuseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TadaNomina.ServiceReferenceTP.StatusUuid[] StatusUuidsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acuse {
            get {
                return this.AcuseField;
            }
            set {
                if ((object.ReferenceEquals(this.AcuseField, value) != true)) {
                    this.AcuseField = value;
                    this.RaisePropertyChanged("Acuse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TadaNomina.ServiceReferenceTP.StatusUuid[] StatusUuids {
            get {
                return this.StatusUuidsField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusUuidsField, value) != true)) {
                    this.StatusUuidsField = value;
                    this.RaisePropertyChanged("StatusUuids");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusUuid", Namespace="http://schemas.datacontract.org/2004/07/PacUtils.Core")]
    [System.SerializableAttribute()]
    public partial class StatusUuid : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid {
            get {
                return this.UuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidField, value) != true)) {
                    this.UuidField = value;
                    this.RaisePropertyChanged("Uuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoConsulta", Namespace="http://schemas.datacontract.org/2004/07/PacUtils.Core")]
    [System.SerializableAttribute()]
    public partial class ResultadoConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcuseCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcuseEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TadaNomina.ServiceReferenceTP.StatusComprobante StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcuseCancelacion {
            get {
                return this.AcuseCancelacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AcuseCancelacionField, value) != true)) {
                    this.AcuseCancelacionField = value;
                    this.RaisePropertyChanged("AcuseCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcuseEnvio {
            get {
                return this.AcuseEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.AcuseEnvioField, value) != true)) {
                    this.AcuseEnvioField = value;
                    this.RaisePropertyChanged("AcuseEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comprobante {
            get {
                return this.ComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprobanteField, value) != true)) {
                    this.ComprobanteField = value;
                    this.RaisePropertyChanged("Comprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TadaNomina.ServiceReferenceTP.StatusComprobante Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusComprobante", Namespace="http://schemas.datacontract.org/2004/07/PacUtils.Core")]
    public enum StatusComprobante : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoEncontrado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnProceso = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enviado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelado = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://turbopac.mx/TurboPac", ConfigurationName="ServiceReferenceTP.ITurboPacWs")]
    public interface ITurboPacWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdiResponse")]
        TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraCfdi(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdiResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraCfdiAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi33", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi33Response")]
        TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraCfdi33(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi33", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraCfdi33Response")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraCfdi33Async(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraURLCfdi33", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraURLCfdi33Response")]
        TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraURLCfdi33(string userName, string password, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraURLCfdi33", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraURLCfdi33Response")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraURLCfdi33Async(string userName, string password, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaCfdi", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaCfdiResponse")]
        TadaNomina.ServiceReferenceTP.RespuestaCancelacion CancelaCfdi(string userName, string password, string requestCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaCfdi", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaCfdiResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaCancelacion> CancelaCfdiAsync(string userName, string password, string requestCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraRetencion", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraRetencionResponse")]
        TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraRetencion(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraRetencion", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/TimbraRetencionResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraRetencionAsync(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaRetencion", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaRetencionResponse")]
        TadaNomina.ServiceReferenceTP.RespuestaCancelacion CancelaRetencion(string userName, string password, string requestCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaRetencion", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/CancelaRetencionResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaCancelacion> CancelaRetencionAsync(string userName, string password, string requestCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/ObtenerStatusUuid", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/ObtenerStatusUuidResponse")]
        TadaNomina.ServiceReferenceTP.ResultadoConsulta ObtenerStatusUuid(string userName, string password, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbopac.mx/TurboPac/ITurboPacWs/ObtenerStatusUuid", ReplyAction="http://turbopac.mx/TurboPac/ITurboPacWs/ObtenerStatusUuidResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.ResultadoConsulta> ObtenerStatusUuidAsync(string userName, string password, string uuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITurboPacWsChannel : TadaNomina.ServiceReferenceTP.ITurboPacWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TurboPacWsClient : System.ServiceModel.ClientBase<TadaNomina.ServiceReferenceTP.ITurboPacWs>, TadaNomina.ServiceReferenceTP.ITurboPacWs {
        
        public TurboPacWsClient() {
        }
        
        public TurboPacWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TurboPacWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurboPacWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurboPacWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraCfdi(string userName, string password, string comprobante) {
            return base.Channel.TimbraCfdi(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraCfdiAsync(string userName, string password, string comprobante) {
            return base.Channel.TimbraCfdiAsync(userName, password, comprobante);
        }
        
        public TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraCfdi33(string userName, string password, string comprobante) {
            return base.Channel.TimbraCfdi33(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraCfdi33Async(string userName, string password, string comprobante) {
            return base.Channel.TimbraCfdi33Async(userName, password, comprobante);
        }
        
        public TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraURLCfdi33(string userName, string password, string url) {
            return base.Channel.TimbraURLCfdi33(userName, password, url);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraURLCfdi33Async(string userName, string password, string url) {
            return base.Channel.TimbraURLCfdi33Async(userName, password, url);
        }
        
        public TadaNomina.ServiceReferenceTP.RespuestaCancelacion CancelaCfdi(string userName, string password, string requestCancelacion) {
            return base.Channel.CancelaCfdi(userName, password, requestCancelacion);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaCancelacion> CancelaCfdiAsync(string userName, string password, string requestCancelacion) {
            return base.Channel.CancelaCfdiAsync(userName, password, requestCancelacion);
        }
        
        public TadaNomina.ServiceReferenceTP.RespuestaTimbrado TimbraRetencion(string userName, string password, string comprobante) {
            return base.Channel.TimbraRetencion(userName, password, comprobante);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaTimbrado> TimbraRetencionAsync(string userName, string password, string comprobante) {
            return base.Channel.TimbraRetencionAsync(userName, password, comprobante);
        }
        
        public TadaNomina.ServiceReferenceTP.RespuestaCancelacion CancelaRetencion(string userName, string password, string requestCancelacion) {
            return base.Channel.CancelaRetencion(userName, password, requestCancelacion);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.RespuestaCancelacion> CancelaRetencionAsync(string userName, string password, string requestCancelacion) {
            return base.Channel.CancelaRetencionAsync(userName, password, requestCancelacion);
        }
        
        public TadaNomina.ServiceReferenceTP.ResultadoConsulta ObtenerStatusUuid(string userName, string password, string uuid) {
            return base.Channel.ObtenerStatusUuid(userName, password, uuid);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP.ResultadoConsulta> ObtenerStatusUuidAsync(string userName, string password, string uuid) {
            return base.Channel.ObtenerStatusUuidAsync(userName, password, uuid);
        }
    }
}
