//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.ServiceReferenceTPJWT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTPJWT.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authenticate", ReplyAction="http://tempuri.org/IService1/AuthenticateResponse")]
        string Authenticate(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authenticate", ReplyAction="http://tempuri.org/IService1/AuthenticateResponse")]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EchoPing", ReplyAction="http://tempuri.org/IService1/EchoPingResponse")]
        string EchoPing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EchoPing", ReplyAction="http://tempuri.org/IService1/EchoPingResponse")]
        System.Threading.Tasks.Task<string> EchoPingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TadaNomina.ServiceReferenceTPJWT.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TadaNomina.ServiceReferenceTPJWT.IService1>, TadaNomina.ServiceReferenceTPJWT.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authenticate(string Username, string password) {
            return base.Channel.Authenticate(Username, password);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string Username, string password) {
            return base.Channel.AuthenticateAsync(Username, password);
        }
        
        public string EchoPing() {
            return base.Channel.EchoPing();
        }
        
        public System.Threading.Tasks.Task<string> EchoPingAsync() {
            return base.Channel.EchoPingAsync();
        }
    }
}
