//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.ServiceReferenceTPCancelacionSinPfx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCancel", Namespace="http://schemas.datacontract.org/2004/07/Tp.OneToOneCancelacion")]
    [System.SerializableAttribute()]
    public partial class ResponseCancel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSeguimiento {
            get {
                return this.IdSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSeguimientoField, value) != true)) {
                    this.IdSeguimientoField = value;
                    this.RaisePropertyChanged("IdSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recib {
            get {
                return this.RecibField;
            }
            set {
                if ((object.ReferenceEquals(this.RecibField, value) != true)) {
                    this.RecibField = value;
                    this.RaisePropertyChanged("Recib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseConsulta", Namespace="http://schemas.datacontract.org/2004/07/Tp.OneToOneCancelacion")]
    [System.SerializableAttribute()]
    public partial class ResponseConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsCancelableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateCancelationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSeguimiento {
            get {
                return this.IdSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSeguimientoField, value) != true)) {
                    this.IdSeguimientoField = value;
                    this.RaisePropertyChanged("IdSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsCancelable {
            get {
                return this.IsCancelableField;
            }
            set {
                if ((object.ReferenceEquals(this.IsCancelableField, value) != true)) {
                    this.IsCancelableField = value;
                    this.RaisePropertyChanged("IsCancelable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateCancelation {
            get {
                return this.StateCancelationField;
            }
            set {
                if ((object.ReferenceEquals(this.StateCancelationField, value) != true)) {
                    this.StateCancelationField = value;
                    this.RaisePropertyChanged("StateCancelation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTPCancelacionSinPfx.ICancelaCert")]
    public interface ICancelaCert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitarCancelacion_01", ReplyAction="http://tempuri.org/ICancelaCert/SolicitarCancelacion_01Response")]
        TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitarCancelacion_01(string rfcEmisor, string uuid, string uuidSustitucion, string PropiedadErronea, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitarCancelacion_01", ReplyAction="http://tempuri.org/ICancelaCert/SolicitarCancelacion_01Response")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitarCancelacion_01Async(string rfcEmisor, string uuid, string uuidSustitucion, string PropiedadErronea, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacion_02", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacion_02Response")]
        TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacion_02(string rfcEmisor, string uuid, string PropiedadErronea, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacion_02", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacion_02Response")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacion_02Async(string rfcEmisor, string uuid, string PropiedadErronea, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacion_03", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacion_03Response")]
        TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacion_03(string rfcEmisor, string uuid, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacion_03", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacion_03Response")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacion_03Async(string rfcEmisor, string uuid, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacion_04", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacion_04Response")]
        TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacion_04(string rfcEmisor, string uuid, string xmlACancelar, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacion_04", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacion_04Response")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacion_04Async(string rfcEmisor, string uuid, string xmlACancelar, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitarConsulta", ReplyAction="http://tempuri.org/ICancelaCert/SolicitarConsultaResponse")]
        TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseConsulta SolicitarConsulta(string rfcEmisor, string rfcReceptor, decimal total, string uuid, string IdSeguimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitarConsulta", ReplyAction="http://tempuri.org/ICancelaCert/SolicitarConsultaResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseConsulta> SolicitarConsultaAsync(string rfcEmisor, string rfcReceptor, decimal total, string uuid, string IdSeguimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacionRetencion", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacionRetencionResponse")]
        TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacionRetencion(string rfcEmisor, string uuid, string motivoDeCancelacion, string uriDescargaXml, byte[] cert, byte[] key, string passCert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICancelaCert/SolicitudCancelacionRetencion", ReplyAction="http://tempuri.org/ICancelaCert/SolicitudCancelacionRetencionResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacionRetencionAsync(string rfcEmisor, string uuid, string motivoDeCancelacion, string uriDescargaXml, byte[] cert, byte[] key, string passCert);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICancelaCertChannel : TadaNomina.ServiceReferenceTPCancelacionSinPfx.ICancelaCert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CancelaCertClient : System.ServiceModel.ClientBase<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ICancelaCert>, TadaNomina.ServiceReferenceTPCancelacionSinPfx.ICancelaCert {
        
        public CancelaCertClient() {
        }
        
        public CancelaCertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CancelaCertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CancelaCertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CancelaCertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitarCancelacion_01(string rfcEmisor, string uuid, string uuidSustitucion, string PropiedadErronea, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitarCancelacion_01(rfcEmisor, uuid, uuidSustitucion, PropiedadErronea, cert, key, passCert);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitarCancelacion_01Async(string rfcEmisor, string uuid, string uuidSustitucion, string PropiedadErronea, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitarCancelacion_01Async(rfcEmisor, uuid, uuidSustitucion, PropiedadErronea, cert, key, passCert);
        }
        
        public TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacion_02(string rfcEmisor, string uuid, string PropiedadErronea, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacion_02(rfcEmisor, uuid, PropiedadErronea, cert, key, passCert);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacion_02Async(string rfcEmisor, string uuid, string PropiedadErronea, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacion_02Async(rfcEmisor, uuid, PropiedadErronea, cert, key, passCert);
        }
        
        public TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacion_03(string rfcEmisor, string uuid, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacion_03(rfcEmisor, uuid, cert, key, passCert);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacion_03Async(string rfcEmisor, string uuid, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacion_03Async(rfcEmisor, uuid, cert, key, passCert);
        }
        
        public TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacion_04(string rfcEmisor, string uuid, string xmlACancelar, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacion_04(rfcEmisor, uuid, xmlACancelar, cert, key, passCert);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacion_04Async(string rfcEmisor, string uuid, string xmlACancelar, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacion_04Async(rfcEmisor, uuid, xmlACancelar, cert, key, passCert);
        }
        
        public TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseConsulta SolicitarConsulta(string rfcEmisor, string rfcReceptor, decimal total, string uuid, string IdSeguimiento) {
            return base.Channel.SolicitarConsulta(rfcEmisor, rfcReceptor, total, uuid, IdSeguimiento);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseConsulta> SolicitarConsultaAsync(string rfcEmisor, string rfcReceptor, decimal total, string uuid, string IdSeguimiento) {
            return base.Channel.SolicitarConsultaAsync(rfcEmisor, rfcReceptor, total, uuid, IdSeguimiento);
        }
        
        public TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel SolicitudCancelacionRetencion(string rfcEmisor, string uuid, string motivoDeCancelacion, string uriDescargaXml, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacionRetencion(rfcEmisor, uuid, motivoDeCancelacion, uriDescargaXml, cert, key, passCert);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTPCancelacionSinPfx.ResponseCancel> SolicitudCancelacionRetencionAsync(string rfcEmisor, string uuid, string motivoDeCancelacion, string uriDescargaXml, byte[] cert, byte[] key, string passCert) {
            return base.Channel.SolicitudCancelacionRetencionAsync(rfcEmisor, uuid, motivoDeCancelacion, uriDescargaXml, cert, key, passCert);
        }
    }
}
