//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdelantoNomina
    {
        public int IdAdelantoNomina { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string concept { get; set; }
        public string transfer_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string status { get; set; }
        public Nullable<int> advance_method_id { get; set; }
        public string advance_method_type { get; set; }
        public string last_four_digits { get; set; }
        public string bank { get; set; }
        public string resp_estado { get; set; }
        public string resp_message { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
    }
}
