//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausentismos
    {
        public int IdAusentismo { get; set; }
        public string Idconcepto { get; set; }
        public string NoFolio { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string FolioIncapacidadInicial { get; set; }
        public string TipoIncapacidad { get; set; }
        public Nullable<System.DateTime> FechaIncio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaInicioAplicacion { get; set; }
        public Nullable<System.DateTime> FechaFinAplicacion { get; set; }
        public Nullable<int> Dias { get; set; }
        public string Archivo { get; set; }
        public string TipoAusentismo { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> DiasSubsidioInicial { get; set; }
        public Nullable<decimal> PorcentajeSubsidioInicial { get; set; }
        public Nullable<decimal> PorcentajeSubsidioRestante { get; set; }
    }
}
