//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Token_MasNegocio
    {
        public int IdToken { get; set; }
        public string Token { get; set; }
        public string URI { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    }
}
