//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_ConceptosNomina
    {
        public int IdConcepto { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdConceptoSistema { get; set; }
        public string ClaveGpo { get; set; }
        public string ClaveConcepto { get; set; }
        public string ClaveSAT { get; set; }
        public string Concepto { get; set; }
        public string Informacion { get; set; }
        public string TipoConcepto { get; set; }
        public string TipoDato { get; set; }
        public string TipoEsquema { get; set; }
        public string CalculaMontos { get; set; }
        public Nullable<decimal> SDPor { get; set; }
        public Nullable<decimal> SDEntre { get; set; }
        public Nullable<int> BanderaSDI { get; set; }
        public string Integrable { get; set; }
        public string IntegraSDI { get; set; }
        public string IntegraISN { get; set; }
        public string AfectaSeldo { get; set; }
        public string AfectaCargaSocial { get; set; }
        public string Exenta { get; set; }
        public string ExentaPorUnidad { get; set; }
        public string UnidadExenta { get; set; }
        public Nullable<decimal> CantidadExenta { get; set; }
        public Nullable<decimal> PorcentajeGravado { get; set; }
        public string SumaNetoFinal { get; set; }
        public string MultiplicaDT { get; set; }
        public string ClaveContable { get; set; }
        public string PagoEfectivo { get; set; }
        public string Piramida { get; set; }
        public string ExentoPorSueldoMinimo { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string CalculoAutomatico { get; set; }
        public string ConceptosCalculo { get; set; }
        public string ConceptosCondicionantesSI { get; set; }
        public string ConceptosCondicionantesNO { get; set; }
        public string FormulaDiasPorcentaje { get; set; }
        public string Formula { get; set; }
        public string IncapacidadPagada { get; set; }
        public Nullable<decimal> DiasIniciales { get; set; }
        public Nullable<decimal> PorcentajeDiasIniciales { get; set; }
        public Nullable<decimal> DiasSubsecuentes { get; set; }
        public Nullable<decimal> PorcentajeDiasSubsecuentes { get; set; }
        public Nullable<int> IdConceptoPago { get; set; }
        public string FactoryValor { get; set; }
        public string CreaConceptoAdicional { get; set; }
        public Nullable<int> IdConceptoAdicional { get; set; }
        public string CalculoDiasHoras { get; set; }
        public string IntegraPension { get; set; }
    }
}
