//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_RegistroPatronal
    {
        public int IdRegistroPatronal { get; set; }
        public int IdCliente { get; set; }
        public string NombrePatrona { get; set; }
        public string RegistroPatronal { get; set; }
        public string RFC { get; set; }
        public int Clase { get; set; }
        public decimal RiesgoTrabajo { get; set; }
        public string Direccion { get; set; }
        public string CP { get; set; }
        public string Pais { get; set; }
        public string EntidadFederativa { get; set; }
        public string Municipio { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public int IdActividadEconomica { get; set; }
        public string SelloDigital { get; set; }
        public string KeyPass { get; set; }
        public string Logo { get; set; }
        public int IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public string rutaCer { get; set; }
        public string rutaKey { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string CuentaBancaria { get; set; }
        public string Sucursal { get; set; }
        public string Plaza { get; set; }
        public string PlazaBanxico { get; set; }
        public string Concepto { get; set; }
        public string EstadoCuenta { get; set; }
        public string ReferenciaOrdenante { get; set; }
        public string FormaAplicacion { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public string PortalWeb { get; set; }
        public Nullable<int> IdReferenciaCliente { get; set; }
        public Nullable<int> IdModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> PersonaFisica { get; set; }
        public string CurpPersonaFisica { get; set; }
        public string CertificadoIMSS { get; set; }
        public string UsuarioIMSS { get; set; }
        public string ContraseñaIMSS { get; set; }
        public string KeyIMSS { get; set; }
        public string PFXCancelacionTimbrado { get; set; }
        public Nullable<int> BanderaEnvioIndividual { get; set; }
        public string NombreRepresentante { get; set; }
        public string rutaFielCer { get; set; }
        public string rutaFielKey { get; set; }
        public string KeyPassFiel { get; set; }
        public string RegimenFiscal { get; set; }
    }
}
