//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteRazonSocialFacturacion
    {
        public int IdClienteRazonSocialFacturacion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IdGrupoFacturacion { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> Idcaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
