//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionConceptosFiniquito
    {
        public int IdConfiguracion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdConceptoVacaciones { get; set; }
        public Nullable<int> IdConceptoPV { get; set; }
        public Nullable<int> IdConceptoAguinaldo { get; set; }
        public Nullable<int> IdConceptoIndem3M { get; set; }
        public Nullable<int> IdConceptoIndem20D { get; set; }
        public Nullable<int> IdConceptoIndemPA { get; set; }
        public Nullable<int> IdConceptoFonacot { get; set; }
        public Nullable<int> IdConceptoInfonavit { get; set; }
        public Nullable<int> IdConceptoPensionAlimenticia { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> idConceptoIncapacidadaccidenteTrayecto { get; set; }
        public Nullable<int> idConceptoEnfermedadGeneral { get; set; }
        public Nullable<int> idConceptoMaternidad { get; set; }
        public Nullable<int> idConceptoRiesgodeTrabajo { get; set; }
        public Nullable<int> idConceptoCuotaSindical { get; set; }
    }
}
