//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionNominaPeriodoEmpleado
    {
        public int IdConfiguracionNomina { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> SupenderSueldoTradicional { get; set; }
        public Nullable<int> SuspenderSueldoEsquema { get; set; }
        public Nullable<int> PagarTodoXEsquema { get; set; }
        public Nullable<int> SuspenderCargasSociales { get; set; }
        public Nullable<decimal> DiasCargaSocial { get; set; }
        public Nullable<decimal> DiasSueldo { get; set; }
        public Nullable<decimal> IncidenciasAutomaticas { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
