//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionFechasCalculos
    {
        public int IdConfiguracion { get; set; }
        public Nullable<int> IdUnidadNegocio { get; set; }
        public string FVacacionesReal { get; set; }
        public string FVacaciones { get; set; }
        public string FVacacionesEsq { get; set; }
        public string FPVReal { get; set; }
        public string FPV { get; set; }
        public string FPVEsq { get; set; }
        public string FAguinaldoReal { get; set; }
        public string FAguinaldo { get; set; }
        public string FAguinaldoEsq { get; set; }
        public string FLiquidacionReal { get; set; }
        public string FLiquidacion { get; set; }
        public string FLiquidacionEsq { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
