//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costeos_Movimientos
    {
        public int IdCosteosMovimiento { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public string Esquema { get; set; }
        public string TipoMovimiento { get; set; }
        public string MovimientoAfecta { get; set; }
        public Nullable<int> IdMovimientoAfecta { get; set; }
        public Nullable<int> IdCosteo { get; set; }
        public Nullable<int> IdPatrona { get; set; }
        public Nullable<int> IdDivision { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
