//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditosInfonavit
    {
        public int IdCreditoInfonavit { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string NumeroCredito { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string FechaAplicacion { get; set; }
        public string CartaRetencion { get; set; }
        public Nullable<decimal> PorcentajeTradicional { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string BanderaSeguroVivienda { get; set; }
    }
}
