//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartamentoPuesto
    {
        public int IdDepartamentoPuesto { get; set; }
        public int IdCliente { get; set; }
        public int IdUnidadNegocio { get; set; }
        public Nullable<int> IdArea { get; set; }
        public int IdDepartamento { get; set; }
        public int IdPuesto { get; set; }
        public int IdNivel { get; set; }
        public int PlazasAutorizadas { get; set; }
        public int IdEstatus { get; set; }
        public int IdCaptura { get; set; }
        public System.DateTime FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
