//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAM_Empleados
    {
        public int IdEmpleado { get; set; }
        public string PersonalJSON { get; set; }
        public Nullable<decimal> CuotaFija { get; set; }
        public Nullable<decimal> CostoHora { get; set; }
        public string JSONMaterias { get; set; }
        public Nullable<decimal> MetaHoras { get; set; }
        public string TipoBono { get; set; }
        public Nullable<decimal> Bono { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
