//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturadoras
    {
        public int IdFacturadora { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdBanco2 { get; set; }
        public string Facturadora { get; set; }
        public string Domicilio { get; set; }
        public string RFC { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaIncioOperacion { get; set; }
        public string ClaveFacturadora { get; set; }
        public string TipoEsquema { get; set; }
        public Nullable<decimal> FacturacionMensual { get; set; }
        public Nullable<decimal> FacturacionAnual { get; set; }
        public string UsuarioMail { get; set; }
        public string PasswordMail { get; set; }
        public Nullable<int> PuertoMail { get; set; }
        public string HostMail { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
