//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Honorarios
    {
        public int IdHonorarios { get; set; }
        public int IdPeriodoNomina { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> HonorariosNetos { get; set; }
        public Nullable<decimal> HonorariosBrutos { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> TotalFactura { get; set; }
        public Nullable<decimal> RetencionISR { get; set; }
        public Nullable<decimal> RetencionIVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string URL_Archivos { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public string MetodoPago { get; set; }
        public string FormaPago { get; set; }
        public string UsoCFDI { get; set; }
        public string EstatusSAT { get; set; }
        public string ObservacionesCliente { get; set; }
        public string ObservacionesUsuario { get; set; }
        public Nullable<int> Aprobado { get; set; }
        public string RFC_Emisor { get; set; }
        public string RFC_Recepctor { get; set; }
        public Nullable<decimal> TotalXML { get; set; }
        public string UUID { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string RutaPDF { get; set; }
        public string RutaXML { get; set; }
    }
}
