//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErrores
    {
        public int IdLogError { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public string Modulo { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    }
}
