//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TadaReportesEntities : DbContext
    {
        public TadaReportesEntities()
            : base("name=TadaReportesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vIncidencias> vIncidencias { get; set; }
        public virtual DbSet<Cat_Reportes> Cat_Reportes { get; set; }
        public virtual DbSet<vEmpleados> vEmpleados { get; set; }
    
        public virtual ObjectResult<sp_ReporteEmpleadosActivos_Result> sp_ReporteEmpleadosActivos(Nullable<int> idUnidadNegocio)
        {
            var idUnidadNegocioParameter = idUnidadNegocio.HasValue ?
                new ObjectParameter("IdUnidadNegocio", idUnidadNegocio) :
                new ObjectParameter("IdUnidadNegocio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReporteEmpleadosActivos_Result>("sp_ReporteEmpleadosActivos", idUnidadNegocioParameter);
        }
    
        public virtual int sp_ReporteNominaGeneral(Nullable<int> idPeriodoNomina)
        {
            var idPeriodoNominaParameter = idPeriodoNomina.HasValue ?
                new ObjectParameter("IdPeriodoNomina", idPeriodoNomina) :
                new ObjectParameter("IdPeriodoNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ReporteNominaGeneral", idPeriodoNominaParameter);
        }
    
        public virtual ObjectResult<sp_ReporteNominaGeneral_Temporal_Result> sp_ReporteNominaGeneral_Temporal(Nullable<int> idPeriodoNomina)
        {
            var idPeriodoNominaParameter = idPeriodoNomina.HasValue ?
                new ObjectParameter("IdPeriodoNomina", idPeriodoNomina) :
                new ObjectParameter("IdPeriodoNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReporteNominaGeneral_Temporal_Result>("sp_ReporteNominaGeneral_Temporal", idPeriodoNominaParameter);
        }
    
        public virtual ObjectResult<sp_CosteoResumenMensual_Result> sp_CosteoResumenMensual(string idsPeriodoNomina)
        {
            var idsPeriodoNominaParameter = idsPeriodoNomina != null ?
                new ObjectParameter("IdsPeriodoNomina", idsPeriodoNomina) :
                new ObjectParameter("IdsPeriodoNomina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CosteoResumenMensual_Result>("sp_CosteoResumenMensual", idsPeriodoNominaParameter);
        }
    }
}
