//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TadaCosteosFacturacionEntities : DbContext
    {
        public TadaCosteosFacturacionEntities()
            : base("name=TadaCosteosFacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_Costeo_Result> sp_Costeo(string idsPeriodoNomina)
        {
            var idsPeriodoNominaParameter = idsPeriodoNomina != null ?
                new ObjectParameter("IdsPeriodoNomina", idsPeriodoNomina) :
                new ObjectParameter("IdsPeriodoNomina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Costeo_Result>("sp_Costeo", idsPeriodoNominaParameter);
        }
    }
}
