//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificacionSueldos
    {
        public int IdModificacionSueldo { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public decimal SDIMSS_Anterior { get; set; }
        public decimal SDI_Anterior { get; set; }
        public decimal SDIMSS_Nuevo { get; set; }
        public decimal SDI_Nuevo { get; set; }
        public string Observaciones { get; set; }
        public int IdCaptura { get; set; }
        public System.DateTime FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> TipoSalario { get; set; }
    }
}
