//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosIMSS
    {
        public int IdMovimiento { get; set; }
        public int IdEmpleado { get; set; }
        public int IdRegistroPatronal { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public Nullable<decimal> SDIMSS { get; set; }
        public Nullable<decimal> SDI { get; set; }
        public string NSS { get; set; }
        public Nullable<int> IdModificacionSueldo { get; set; }
        public Nullable<int> Envio { get; set; }
        public string CodigoERROREnvio { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Lote { get; set; }
        public Nullable<int> RespuestaLote { get; set; }
        public string CodigoERRORRespuesta { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string IdEstatus { get; set; }
        public int IdCaptura { get; set; }
        public System.DateTime FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> BanderaArchivo { get; set; }
        public string ClienteAdministrado { get; set; }
    }
}
