//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaProvision
    {
        public int IdPeriodoNomina { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<decimal> DiasAguinaldo { get; set; }
        public Nullable<decimal> DiasVacaciones { get; set; }
        public Nullable<decimal> PorcentajePV { get; set; }
        public Nullable<decimal> ProvisionAguinaldo { get; set; }
        public Nullable<decimal> ProvisionVacaciones { get; set; }
        public Nullable<decimal> ProvisionPrimaVacacional { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
    }
}
