//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoNomina
    {
        public int IdPeriodoNomina { get; set; }
        public int IdUnidadNegocio { get; set; }
        public string Periodo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<System.DateTime> FechaInicioChecador { get; set; }
        public Nullable<System.DateTime> FechaFinChecador { get; set; }
        public string Observaciones { get; set; }
        public string NominaTimbrada { get; set; }
        public string RecibosComplemento { get; set; }
        public string TipoNomina { get; set; }
        public string AjusteDeImpuestos { get; set; }
        public string SeAjustaraConPeriodo { get; set; }
        public string DescuentosFijos { get; set; }
        public int NuevaIncidencia { get; set; }
        public int TotalEmpleados { get; set; }
        public decimal TotalISR { get; set; }
        public decimal TotalIMSSObrero { get; set; }
        public decimal TotalIMSSPatronal { get; set; }
        public decimal TotalISN { get; set; }
        public decimal ImporteNeto { get; set; }
        public int IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<System.DateTime> FechaDispersion { get; set; }
        public string RecibosEsquema { get; set; }
        public string Costeado { get; set; }
        public string Dispersion { get; set; }
        public Nullable<int> IdDispersion { get; set; }
        public Nullable<int> IdCliente_PTU { get; set; }
        public Nullable<int> IdRegistroPatronal_PTU { get; set; }
        public Nullable<decimal> Monto_PTU { get; set; }
        public Nullable<int> Año_PTU { get; set; }
        public string AjusteAnual { get; set; }
        public string TablaDiaria { get; set; }
        public string EmpleadosSinAjuste { get; set; }
        public string PeriodosAjusteSecundario { get; set; }
        public string PeriodosIntegracionSDI { get; set; }
        public string BanderaNoVacaciones { get; set; }
        public string BanderaNoPV { get; set; }
        public string BanderaNoAguinaldo { get; set; }
        public string BanderaNo90Dias { get; set; }
        public string BanderaNo20Dias { get; set; }
        public string BanderaNoPA { get; set; }
    }
}
