//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecuperacionIMSS
    {
        public int IdRecuperaIMSS { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Observaciones { get; set; }
        public string TipoRecuperacion { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdCaptura { get; set; }
    }
}
