//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMail
    {
        public int idSendMail { get; set; }
        public string Proyecto { get; set; }
        public string Credentials { get; set; }
        public string Contrasena { get; set; }
        public string ClientHost { get; set; }
        public string Puerto { get; set; }
        public Nullable<int> Idestatus { get; set; }
    }
}
