//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sindicatos
    {
        public int IdSindicato { get; set; }
        public string NombreSindicato { get; set; }
        public string NombreCorto { get; set; }
        public Nullable<int> Grupo { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdModificacion { get; set; }
        public string CuentaBancaria { get; set; }
        public Nullable<int> RegActivo { get; set; }
    }
}
