//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsidioEmpleoSat
    {
        public int IdSubsidio { get; set; }
        public int IdTipoNomina { get; set; }
        public decimal LimiteInferior { get; set; }
        public decimal LimiteSuperior { get; set; }
        public decimal CreditoSalario { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    }
}
