//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldos_Minimos
    {
        public int IdSueldoMinimo { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<decimal> SalarioMinimoGeneral { get; set; }
        public Nullable<decimal> UMA { get; set; }
        public Nullable<decimal> UnidadMixta { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
    }
}
