//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimbradoNomina
    {
        public int IdTimbradoNomina { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public string RegistroPatronal { get; set; }
        public string NombrePatrona { get; set; }
        public string RFC { get; set; }
        public string FechaTimbrado { get; set; }
        public string FolioUDDI { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> AnioMes { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaInicioPeriodo { get; set; }
        public Nullable<System.DateTime> FechaFinPeriodo { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string CFDI_Timbrado { get; set; }
        public string ClaveMotivoCancelacion { get; set; }
        public string AcuseCancelacion { get; set; }
        public string CodigoRespuestaCancelacion { get; set; }
        public string MensajeCancelacion { get; set; }
        public string Leyenda { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
        public Nullable<int> IdMotivoCancelacion { get; set; }
        public string UUID_Relacionado { get; set; }
        public Nullable<int> IdXml { get; set; }
        public Nullable<int> IdPAC { get; set; }
    }
}
