//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        public string IdCliente { get; set; }
        public string IdUnidadNegocio { get; set; }
        public string IdCentroCostos { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Correo { get; set; }
        public string Usuario { get; set; }
        public byte[] Contraseña { get; set; }
        public string TipoUsuario { get; set; }
        public string Inventarios { get; set; }
        public string MovimientosEspeciales { get; set; }
        public string RHCloud { get; set; }
        public string RelogChecador { get; set; }
        public Nullable<int> Cordinador { get; set; }
        public Nullable<int> Confidencial { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Evaluacion { get; set; }
        public Nullable<int> Soporte { get; set; }
        public byte[] ImagenUsuario { get; set; }
    }
}
