//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Costeos_Grupos_Facturadoras
    {
        public int IdGrupoFacturacion { get; set; }
        public string Grupo { get; set; }
        public string Observaciones { get; set; }
        public string Facturadora { get; set; }
        public int IdFacturadora { get; set; }
        public string TipoEsquema { get; set; }
        public int IdEstatus { get; set; }
    }
}
