//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_IMSS_MovimientosCESS
    {
        public Nullable<double> Lote { get; set; }
        public string NombrePatrona { get; set; }
        public string RFC_Patrona { get; set; }
        public string RegistroPatronal { get; set; }
        public string ActividadEconomica { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> SDI { get; set; }
        public string Imss { get; set; }
        public string TipoSemana { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public Nullable<System.DateTime> FechaTransmision { get; set; }
        public Nullable<double> TipoMovimiento { get; set; }
        public string Movimiento { get; set; }
        public string CausaBaja { get; set; }
        public string Origen { get; set; }
    }
}
