//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCompensaciones
    {
        public int IdCompensacion { get; set; }
        public int IdArea { get; set; }
        public int IdPeridoNomina { get; set; }
        public int IdEmpleado { get; set; }
        public int IdConceptoCompensacion { get; set; }
        public int IdConceptoNomina { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Importe { get; set; }
        public int IdEstatus { get; set; }
        public int IdCaptura { get; set; }
        public System.DateTime FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
