//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vConfiguracionConceptosFiniquitos
    {
        public int IdConfiguracion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdConceptoVacaciones { get; set; }
        public Nullable<int> IdConceptoPV { get; set; }
        public Nullable<int> IdConceptoAguinaldo { get; set; }
        public Nullable<int> IdConceptoIndem3M { get; set; }
        public Nullable<int> IdConceptoIndem20D { get; set; }
        public Nullable<int> IdConceptoIndemPA { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string ClaveConceptoVac { get; set; }
        public string ConceptoVac { get; set; }
        public string ClaveConceptoPV { get; set; }
        public string ConceptoPV { get; set; }
        public string ClaveConceptoAguinaldo { get; set; }
        public string ConceptoAguinaldo { get; set; }
        public string ClaveConcepto3M { get; set; }
        public string Concepto3M { get; set; }
        public string ClaveConcepto20D { get; set; }
        public string Concepto20D { get; set; }
        public string ClaveConceptoPA { get; set; }
        public string ConceptoPA { get; set; }
        public Nullable<int> IdConceptoFonacot { get; set; }
        public Nullable<int> IdConceptoInfonavit { get; set; }
        public Nullable<int> IdConceptoPensionAlimenticia { get; set; }
        public string ClaveConceptoFonacot { get; set; }
        public string ConceptoFonacot { get; set; }
        public string ClaveConceptoInfonavit { get; set; }
        public string ConceptoInfonavit { get; set; }
        public string ClaveConceptoPensionAlimenticia { get; set; }
        public string ConceptoPensionAlimenticia { get; set; }
        public Nullable<int> idConceptoIncapacidadaccidenteTrayecto { get; set; }
        public Nullable<int> idConceptoEnfermedadGeneral { get; set; }
        public Nullable<int> idConceptoMaternidad { get; set; }
        public Nullable<int> idConceptoRiesgodeTrabajo { get; set; }
        public Nullable<int> idConceptoCuotaSindical { get; set; }
    }
}
