//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vConfiguracionConceptosFiniquitos
    {
        public int IdConfiguracion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdConceptoVacaciones { get; set; }
        public Nullable<int> IdConceptoPV { get; set; }
        public Nullable<int> IdConceptoAguinaldo { get; set; }
        public Nullable<int> IdConceptoIndem3M { get; set; }
        public Nullable<int> IdConceptoIndem20D { get; set; }
        public Nullable<int> IdConceptoIndemPA { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string ClaveConceptoVac { get; set; }
        public string ConceptoVac { get; set; }
        public string ClaveConceptoPV { get; set; }
        public string ConceptoPV { get; set; }
        public string ClaveConceptoAguinaldo { get; set; }
        public string ConceptoAguinaldo { get; set; }
        public string ClaveConcepto3M { get; set; }
        public string Concepto3M { get; set; }
        public string ClaveConcepto20D { get; set; }
        public string Concepto20D { get; set; }
        public string ClaveConceptoPA { get; set; }
        public string ConceptoPA { get; set; }
        public Nullable<int> IdConceptoFonacot { get; set; }
        public Nullable<int> IdConceptoInfonavit { get; set; }
        public Nullable<int> IdConceptoPensionAlimenticia { get; set; }
        public string ClaveConceptoFonacot { get; set; }
        public string ConceptoFonacot { get; set; }
        public string ClaveConceptoInfonavit { get; set; }
        public string ConceptoInfonavit { get; set; }
        public string ClaveConceptoPensionAlimenticia { get; set; }
        public string ConceptoPensionAlimenticia { get; set; }
        public Nullable<int> idConceptoIncapacidadaccidenteTrayecto { get; set; }
        public Nullable<int> idConceptoEnfermedadGeneral { get; set; }
        public Nullable<int> idConceptoMaternidad { get; set; }
        public Nullable<int> idConceptoRiesgodeTrabajo { get; set; }
        public Nullable<int> idConceptoCuotaSindical { get; set; }
        public Nullable<int> IdConceptoCompensacion { get; set; }
        public string ClaveConceptoCompensacion { get; set; }
        public string ConceptoCompensacion { get; set; }
        public Nullable<int> IdConceptoFaltas { get; set; }
        public string ClaveConceptoFalta { get; set; }
        public string ConceptoFalta { get; set; }
        public Nullable<int> IdConceptoArt93Fraclll { get; set; }
        public string ClaveConceptoArt93Fraclll { get; set; }
        public string ConceptoArt93Fraclll { get; set; }
        public Nullable<int> IdConceptoSubsidioIncapacidad { get; set; }
        public Nullable<int> idConceptoSeptimoDia { get; set; }
        public Nullable<int> IdConceptoDiasDevengadosFiniquitos { get; set; }
        public string ClaveConceptoDiasDevengadosFiniquitos { get; set; }
    }
}
