//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vConfiguracionFiniquito
    {
        public int IdEmpleado { get; set; }
        public string ClaveEmpleado { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public string Rfc { get; set; }
        public Nullable<System.DateTime> FechaAltaIMSS { get; set; }
        public Nullable<System.DateTime> FechaReconocimientoAntiguedad { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public Nullable<int> IdConfiguracionFiniquito { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public Nullable<System.DateTime> FechaBajaFin { get; set; }
        public Nullable<int> BanderaVac { get; set; }
        public Nullable<int> BanderaPV { get; set; }
        public Nullable<int> BanderaAguinaldo { get; set; }
        public Nullable<int> BanderaLiquidacion { get; set; }
        public Nullable<int> Bandera90d { get; set; }
        public Nullable<int> Bandera20d { get; set; }
        public Nullable<int> BanderaPA { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<decimal> ER { get; set; }
        public Nullable<decimal> DD { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> ERS { get; set; }
        public Nullable<decimal> DDS { get; set; }
        public Nullable<decimal> Netos { get; set; }
        public int IdUnidadNegocio { get; set; }
        public Nullable<int> BanderaPVEsq { get; set; }
        public Nullable<int> BanderaAguinaldoEsq { get; set; }
        public Nullable<int> IdEstatusNomina { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> LiquidacionSDI { get; set; }
        public Nullable<int> BanderaExentoProporcionalLiquidacion { get; set; }
    }
}
