//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCosteos_Fondeos
    {
        public int IdOtroConcepto { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public Nullable<int> IdUnidadNegocio { get; set; }
        public Nullable<int> IdCosteo { get; set; }
        public Nullable<int> IdPatrona { get; set; }
        public Nullable<int> IdDivision { get; set; }
        public string Esquema { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Conceptos { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string Expr1 { get; set; }
        public string TipoNomina { get; set; }
        public string DividirPatronal { get; set; }
        public string SeparadoPor { get; set; }
    }
}
