//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCreditoFonacot
    {
        public int IdCreditoFonacot { get; set; }
        public int IdEmpleado { get; set; }
        public string ClaveEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Rfc { get; set; }
        public string Curp { get; set; }
        public string NoTrabajadorFonacot { get; set; }
        public string NumeroCredito { get; set; }
        public Nullable<decimal> CuotasPagadas { get; set; }
        public Nullable<int> Plazos { get; set; }
        public Nullable<decimal> RetencionMensual { get; set; }
        public string NombrePatrona { get; set; }
        public string RegistroPatronal { get; set; }
        public int IdUnidadNegocio { get; set; }
        public string UnidadNegocio { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    }
}
