//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDesgloceVacaciones
    {
        public int IdDesglose { get; set; }
        public int IdSolicitud { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public decimal Periodo { get; set; }
        public int IdEstatus { get; set; }
        public int IdCaptura { get; set; }
        public System.DateTime FechaCaptura { get; set; }
        public int IdEstatusEmpleado { get; set; }
        public int IdUnidadNegocio { get; set; }
    }
}
