//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIncidenciasProgramadas
    {
        public int IdIncidenciasProgramadas { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoEsq { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string ClaveGpo { get; set; }
        public string ClaveConcepto { get; set; }
        public string ClaveSAT { get; set; }
        public string Concepto { get; set; }
        public string Informacion { get; set; }
        public string TipoConcepto { get; set; }
        public string TipoDato { get; set; }
        public string TipoEsquema { get; set; }
        public string CalculaMontos { get; set; }
        public Nullable<decimal> SDPor { get; set; }
        public Nullable<decimal> SDEntre { get; set; }
        public string Integrable { get; set; }
        public string IntegraSDI { get; set; }
        public string AfectaSeldo { get; set; }
        public string AfectaCargaSocial { get; set; }
        public string Exenta { get; set; }
        public string UnidadExenta { get; set; }
        public Nullable<decimal> CantidadExenta { get; set; }
        public Nullable<decimal> PorcentajeGravado { get; set; }
        public string ClaveEmpleado { get; set; }
        public string NombreCompleto { get; set; }
        public string Curp { get; set; }
        public string Rfc { get; set; }
        public string Imss { get; set; }
        public string CentroCostos { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public int IdUnidadNegocio { get; set; }
        public Nullable<int> IdCentroCostos { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public int IdEntidad { get; set; }
    }
}
