//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNominaSelectFiniquito
    {
        public int IdEmpleado { get; set; }
        public int IdPeriodoNomina { get; set; }
        public Nullable<decimal> ER { get; set; }
        public Nullable<decimal> DD { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> ERS { get; set; }
        public Nullable<decimal> DDS { get; set; }
        public Nullable<decimal> Netos { get; set; }
        public string ClaveEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public int IdUnidadNegocio { get; set; }
        public string Periodo { get; set; }
        public string TipoNomina { get; set; }
    }
}
