//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPensionAlimenticia
    {
        public int IdPensionAlimenticia { get; set; }
        public string TipoPension { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> ValorEsq { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public string NombreBeneficiario { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public int IdEmpleado { get; set; }
        public string ClaveEmpleado { get; set; }
        public string NombreCompleto { get; set; }
        public string Curp { get; set; }
        public string Imss { get; set; }
        public string Rfc { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public string CentroCostos { get; set; }
        public string Banco { get; set; }
        public string Cliente { get; set; }
        public string UnidadNegocio { get; set; }
        public int IdUnidadNegocio { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> idBasePension { get; set; }
        public string Activo { get; set; }
    }
}
