//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSaldos
    {
        public int IdSaldo { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<decimal> SaldoInicial { get; set; }
        public Nullable<decimal> SaldoActual { get; set; }
        public Nullable<decimal> SaldoTotal { get; set; }
        public Nullable<decimal> DescuentoPeriodo { get; set; }
        public Nullable<decimal> NumeroPeriodos { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string ClaveEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Curp { get; set; }
        public string Rfc { get; set; }
        public string Imss { get; set; }
        public int IdUnidadNegocio { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public string ClaveConcepto { get; set; }
        public string ClaveSAT { get; set; }
        public string Concepto { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Indefinido { get; set; }
        public string Observaciones { get; set; }
        public int IdEstatusEmpleado { get; set; }
        public string Activo { get; set; }
    }
}
