//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTimbradoNomina
    {
        public int IdTimbradoNomina { get; set; }
        public Nullable<int> IdPeriodoNomina { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public string RegistroPatronal { get; set; }
        public string NombrePatrona { get; set; }
        public string RFC { get; set; }
        public string FechaTimbrado { get; set; }
        public string FolioUDDI { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> AnioMes { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaInicioPeriodo { get; set; }
        public Nullable<System.DateTime> FechaFinPeriodo { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string CFDI_Timbrado { get; set; }
        public string Leyenda { get; set; }
        public string RFC_Patronal { get; set; }
        public int Clase { get; set; }
        public decimal RiesgoTrabajo { get; set; }
        public string Direccion { get; set; }
        public string CP { get; set; }
        public string Pais { get; set; }
        public string EntidadFederativa { get; set; }
        public string Municipio { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public int IdActividadEconomica { get; set; }
        public string SelloDigital { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public string ClaveEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> IdBancoTrad { get; set; }
        public string ClaveBanco { get; set; }
        public string NombreCorto { get; set; }
        public string CuentaBancariaTrad { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
        public string Periodo { get; set; }
        public string MensajeCancelacion { get; set; }
        public string CodigoRespuestaCancelacion { get; set; }
        public string AcuseCancelacion { get; set; }
        public string ClaveMotivoCancelacion { get; set; }
        public string PFXCancelacionTimbrado { get; set; }
        public string KeyPass { get; set; }
        public string rutaCer { get; set; }
        public string rutaKey { get; set; }
        public Nullable<decimal> SueldoMensual { get; set; }
        public Nullable<int> IdCentroCostos { get; set; }
        public string CentroCostos { get; set; }
        public Nullable<int> IdXml { get; set; }
        public string TipoNomina { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> SD { get; set; }
        public Nullable<int> idSincatosClientes { get; set; }
        public string BanderaSindicalizados { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public int IdEntidad { get; set; }
    }
}
