//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ArchivosAltaCuentas
    {
        public int IdArchivoAltas { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdUnidadNegocio { get; set; }
        public string Ruta { get; set; }
        public string Observaciones { get; set; }
        public string ObservacionesTesoreria { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCaptura { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<int> IdRechazo { get; set; }
        public Nullable<System.DateTime> FechaRechazo { get; set; }
        public Nullable<int> IdFinaliza { get; set; }
        public Nullable<System.DateTime> FechaFinaliza { get; set; }
        public string Cliente { get; set; }
        public string UnidadNegocio { get; set; }
        public string UsuarioCaptura { get; set; }
        public string UsuarioRechazo { get; set; }
        public string UsuarioFinaliza { get; set; }
        public string Estatus { get; set; }
    }
}
