name: Build and Deploy - Nomina Monolitico Azure

env:
  AZURE_WEBAPP_NAME: "monolito-nomina"
  AZURE_WEBAPP_PACKAGE_PATH: '.'

on:
  push:
    branches: [ "azure-deploy" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: nuget restore D:\a\TadaNomina\TadaNomina.sln
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build and publish
        run: msbuild  D:\a\TadaNomina\TadaNomina.sln /p:Configuration=Release /p:DeployOnBuild=true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          path: D:\a\TadaNomina\TadaNomina\bin\Release
