//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TadaNomina.ServiceReferenceTP40 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseSealed", Namespace="http://schemas.datacontract.org/2004/07/Tp.OneToOneCFDI40")]
    [System.SerializableAttribute()]
    public partial class ResponseSealed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcuseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimbradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrueFalseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acuse {
            get {
                return this.AcuseField;
            }
            set {
                if ((object.ReferenceEquals(this.AcuseField, value) != true)) {
                    this.AcuseField = value;
                    this.RaisePropertyChanged("Acuse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeError {
            get {
                return this.CodeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeErrorField, value) != true)) {
                    this.CodeErrorField = value;
                    this.RaisePropertyChanged("CodeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageError {
            get {
                return this.MessageErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageErrorField, value) != true)) {
                    this.MessageErrorField = value;
                    this.RaisePropertyChanged("MessageError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Timbrado {
            get {
                return this.TimbradoField;
            }
            set {
                if ((object.ReferenceEquals(this.TimbradoField, value) != true)) {
                    this.TimbradoField = value;
                    this.RaisePropertyChanged("Timbrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrueFalse {
            get {
                return this.TrueFalseField;
            }
            set {
                if ((this.TrueFalseField.Equals(value) != true)) {
                    this.TrueFalseField = value;
                    this.RaisePropertyChanged("TrueFalse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTP40.ISealedTurboPac")]
    public interface ISealedTurboPac {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/SealedCFDI40", ReplyAction="http://tempuri.org/ISealedTurboPac/SealedCFDI40Response")]
        TadaNomina.ServiceReferenceTP40.ResponseSealed SealedCFDI40(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/SealedCFDI40", ReplyAction="http://tempuri.org/ISealedTurboPac/SealedCFDI40Response")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP40.ResponseSealed> SealedCFDI40Async(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/SealedRetencion", ReplyAction="http://tempuri.org/ISealedTurboPac/SealedRetencionResponse")]
        TadaNomina.ServiceReferenceTP40.ResponseSealed SealedRetencion(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/SealedRetencion", ReplyAction="http://tempuri.org/ISealedTurboPac/SealedRetencionResponse")]
        System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP40.ResponseSealed> SealedRetencionAsync(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateXMLCFDI40", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateXMLCFDI40Response")]
        string ValidateXMLCFDI40(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateXMLCFDI40", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateXMLCFDI40Response")]
        System.Threading.Tasks.Task<string> ValidateXMLCFDI40Async(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateXMLRET20", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateXMLRET20Response")]
        string ValidateXMLRET20(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateXMLRET20", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateXMLRET20Response")]
        System.Threading.Tasks.Task<string> ValidateXMLRET20Async(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateStructRET", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateStructRETResponse")]
        string ValidateStructRET(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateStructRET", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateStructRETResponse")]
        System.Threading.Tasks.Task<string> ValidateStructRETAsync(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateStructCFDI", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateStructCFDIResponse")]
        string ValidateStructCFDI(string xScript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISealedTurboPac/ValidateStructCFDI", ReplyAction="http://tempuri.org/ISealedTurboPac/ValidateStructCFDIResponse")]
        System.Threading.Tasks.Task<string> ValidateStructCFDIAsync(string xScript);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISealedTurboPacChannel : TadaNomina.ServiceReferenceTP40.ISealedTurboPac, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SealedTurboPacClient : System.ServiceModel.ClientBase<TadaNomina.ServiceReferenceTP40.ISealedTurboPac>, TadaNomina.ServiceReferenceTP40.ISealedTurboPac {
        
        public SealedTurboPacClient() {
        }
        
        public SealedTurboPacClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SealedTurboPacClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SealedTurboPacClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SealedTurboPacClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TadaNomina.ServiceReferenceTP40.ResponseSealed SealedCFDI40(string xScript) {
            return base.Channel.SealedCFDI40(xScript);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP40.ResponseSealed> SealedCFDI40Async(string xScript) {
            return base.Channel.SealedCFDI40Async(xScript);
        }
        
        public TadaNomina.ServiceReferenceTP40.ResponseSealed SealedRetencion(string xScript) {
            return base.Channel.SealedRetencion(xScript);
        }
        
        public System.Threading.Tasks.Task<TadaNomina.ServiceReferenceTP40.ResponseSealed> SealedRetencionAsync(string xScript) {
            return base.Channel.SealedRetencionAsync(xScript);
        }
        
        public string ValidateXMLCFDI40(string xScript) {
            return base.Channel.ValidateXMLCFDI40(xScript);
        }
        
        public System.Threading.Tasks.Task<string> ValidateXMLCFDI40Async(string xScript) {
            return base.Channel.ValidateXMLCFDI40Async(xScript);
        }
        
        public string ValidateXMLRET20(string xScript) {
            return base.Channel.ValidateXMLRET20(xScript);
        }
        
        public System.Threading.Tasks.Task<string> ValidateXMLRET20Async(string xScript) {
            return base.Channel.ValidateXMLRET20Async(xScript);
        }
        
        public string ValidateStructRET(string xScript) {
            return base.Channel.ValidateStructRET(xScript);
        }
        
        public System.Threading.Tasks.Task<string> ValidateStructRETAsync(string xScript) {
            return base.Channel.ValidateStructRETAsync(xScript);
        }
        
        public string ValidateStructCFDI(string xScript) {
            return base.Channel.ValidateStructCFDI(xScript);
        }
        
        public System.Threading.Tasks.Task<string> ValidateStructCFDIAsync(string xScript) {
            return base.Channel.ValidateStructCFDIAsync(xScript);
        }
    }
}
